export const LOGIN_USER_FETCHED = 'STUFFIE:LOGIN_USER_FETCHED';
export const USER_FETCHED = 'STUFFIE:USER_FETCHED';
export const USER_REQUESTS_FETCHED = 'STUFFIE:USER_REQUESTS_FETCHED';
export const USER_REQUEST_DELETED = 'STUFFIE::USER_REQUEST_DELETED';
