export const LOGIN_USER_FETCHED = 'STUFFIE:LOGIN_USER_FETCHED';
export const USER_FETCHED = 'STUFFIE:USER_FETCHED';
export const USER_REGISTERED = 'STUFFIE:USER_REGISTERED';
export const USER_PICTURE_ADDED = 'STUFFIE:USER_PICTURE_ADDED';
export const USER_UPDATED = 'STUFFIE:USER_UPDATED';
